/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 03f4b0d61b423eca1619d2e73b0c4aee)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	APP_ENV: string;
	APP_DOMAIN: string;
	AUTH_MODE: string;
	TRUSTED_CLIENT_IP_HEADER: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "APP_DOMAIN" | "AUTH_MODE" | "TRUSTED_CLIENT_IP_HEADER">> {}
}
