/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 083f7afab151ac80b80395f3bed91ea6)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	APP_ENV: "preview";
	APP_DOMAIN: "dft.jarvisworlds.com";
	AUTH_MODE: "disabled";
	TRUSTED_CLIENT_IP_HEADER: "cf-connecting-ip";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "APP_DOMAIN" | "AUTH_MODE" | "TRUSTED_CLIENT_IP_HEADER">> {}
}
