/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.breach-scan.example.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=BreachScanWorkerEnv workers/breach-scan-env.d.ts` (hash: 92095b613f8776efd2aa02bfbc47f900)
interface __BaseEnv_BreachScanWorkerEnv {
	SCAN_DATABASE: Hyperdrive;
	SCAN_KILL_SWITCH: string;
	SCAN_SYNTHETIC_ENABLED: string;
	SCAN_CLAIM_BATCH_SIZE: string;
	SCAN_CLAIM_LEASE_SECONDS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./breach-scan");
	}
	interface Env extends __BaseEnv_BreachScanWorkerEnv {}
}
interface BreachScanWorkerEnv extends __BaseEnv_BreachScanWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SCAN_KILL_SWITCH" | "SCAN_SYNTHETIC_ENABLED" | "SCAN_CLAIM_BATCH_SIZE" | "SCAN_CLAIM_LEASE_SECONDS">> {}
}
