/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.retention.example.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=RetentionWorkerEnv workers/retention-env.d.ts` (hash: 99b0c9276e9d19c3e499683cb5d4fe88)
interface __BaseEnv_RetentionWorkerEnv {
	MAINTENANCE_DATABASE: Hyperdrive;
	RETENTION_BATCH_SIZE: string;
	ORPHAN_AUDIT_RETENTION_DAYS: string;
	SCAN_JOB_RETENTION_DAYS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./retention");
	}
	interface Env extends __BaseEnv_RetentionWorkerEnv {}
}
interface RetentionWorkerEnv extends __BaseEnv_RetentionWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RETENTION_BATCH_SIZE" | "ORPHAN_AUDIT_RETENTION_DAYS" | "SCAN_JOB_RETENTION_DAYS">> {}
}
