/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.verification-delivery.example.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=VerificationDeliveryWorkerEnv workers/verification-delivery-env.d.ts` (hash: db89d510b2d1a9a8bd72336c21a7b76c)
interface __BaseEnv_VerificationDeliveryWorkerEnv {
	DELIVERY_DATABASE: Hyperdrive;
	DELIVERY_ENCRYPTION_KEY: SecretsStoreSecret;
	DELIVERY_ENCRYPTION_KEY_ID: string;
	DELIVERY_KILL_SWITCH: string;
	DELIVERY_CLAIM_BATCH_SIZE: string;
	DELIVERY_CLAIM_LEASE_SECONDS: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./verification-delivery");
	}
	interface Env extends __BaseEnv_VerificationDeliveryWorkerEnv {}
}
interface VerificationDeliveryWorkerEnv extends __BaseEnv_VerificationDeliveryWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DELIVERY_ENCRYPTION_KEY_ID" | "DELIVERY_KILL_SWITCH" | "DELIVERY_CLAIM_BATCH_SIZE" | "DELIVERY_CLAIM_LEASE_SECONDS">> {}
}
